version: 2
jobs:
  build:
    branches:
      only:
        - release
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - checkout
      - run:
          name: Deploy to S3 if branch is release.
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              aws s3 sync ~/repo s3://${AWS_S3_BUCKET_NAME}/ --exact-timestamps --delete
            fi
